version: "3.1"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env